import type { Student, Material } from '@/types';

export const materials: Material[] = [
  { id: '1', name: 'Mattress', required: true },
  { id: '2', name: 'Pillow', required: true },
  { id: '3', name: 'Bed Sheets (2 pairs)', required: true },
  { id: '4', name: 'Blanket', required: true },
  { id: '5', name: 'Mosquito Net', required: true },
  { id: '6', name: 'Bucket and Basin', required: true },
  { id: '7', name: 'Toiletries', required: true },
  { id: '8', name: 'School Uniform', required: true },
  { id: '9', name: 'Sports Wear', required: true },
  { id: '10', name: 'Textbooks', required: false },
];

export const students: Student[] = [
  {
    id: 'S001',
    name: 'John Doe',
    class: 'Grade 10A',
    type: 'boarding',
    parentName: 'Jane Doe',
    parentPhone: '123-456-7890',
    location: 'Capital City',
    feesPaid: 1500,
    totalFees: 2000,
    refectoryTable: 12,
    gender: 'male',
    utilities: [
      { materialId: '1', status: 'present' },
      { materialId: '2', status: 'present' },
      { materialId: '3', status: 'missing' },
      { materialId: '4', status: 'present' },
    ],
  },
  {
    id: 'S002',
    name: 'Alice Smith',
    class: 'Grade 11B',
    type: 'external',
    parentName: 'Robert Smith',
    parentPhone: '234-567-8901',
    location: 'Suburbia',
    feesPaid: 2000,
    totalFees: 2000,
    refectoryTable: 25,
    gender: 'female',
    utilities: [],
  },
  {
    id: 'S003',
    name: 'Michael Johnson',
    class: 'Grade 9C',
    type: 'boarding',
    parentName: 'Mary Johnson',
    parentPhone: '345-678-9012',
    location: 'Downtown',
    feesPaid: 1800,
    totalFees: 2000,
    refectoryTable: 5,
    gender: 'male',
    utilities: [
      { materialId: '1', status: 'present' },
      { materialId: '2', status: 'present' },
      { materialId: '3', status: 'present' },
      { materialId: '4', status: 'present' },
    ],
  },
    {
    id: 'S004',
    name: 'Emily Brown',
    class: 'Grade 12A',
    type: 'boarding',
    parentName: 'William Brown',
    parentPhone: '456-789-0123',
    location: 'Countryside',
    feesPaid: 2000,
    totalFees: 2000,
    refectoryTable: 18,
    gender: 'female',
    utilities: [
      { materialId: '1', status: 'present' },
      { materialId: '2', status: 'missing' },
      { materialId: '3', status: 'missing' },
      { materialId: '4', status: 'present' },
    ],
  },
  {
    id: 'S005',
    name: 'David Wilson',
    class: 'Grade 10A',
    type: 'external',
    parentName: 'Susan Wilson',
    parentPhone: '567-890-1234',
    location: 'Capital City',
    feesPaid: 1900,
    totalFees: 2000,
    refectoryTable: 33,
    gender: 'male',
    utilities: [],
  },
    {
    id: 'S006',
    name: 'Sophia Miller',
    class: 'Grade 11B',
    type: 'boarding',
    parentName: 'James Miller',
    parentPhone: '678-901-2345',
    location: 'Metropolis',
    feesPaid: 1200,
    totalFees: 2000,
    refectoryTable: 7,
    gender: 'female',
    utilities: [
      { materialId: '1', status: 'present' },
      { materialId: '2', status: 'present' },
      { materialId: '3', status: 'present' },
      { materialId: '4', status: 'missing' },
    ],
  },
];
